### ISSUE TITLE
New NegCLIP variants

### ISSUE THREAD

**Issue by vishaal27** [RAIVNLab/sugar-crepe#1]
Hey,

Thanks so much for your super interesting benchmark and analysis. I wanted to play around with the newer variants of the NegCLIP models that you trained from scratch and fine-tuned (the models you use for the numbers in Table 5 of the paper), are you planning to release the weights for all these models? It would be highly appreciated!

Thanks!

**Comment by JieyuZ2** [comment]
Sure, we will release them asap.

**Comment by JieyuZ2** [comment]
released, please see the readme

**Comment by vishaal27** [comment]
Hi, thanks for releasing the models. I have a question regarding the specific models you trained---what are the different models like t30-swap, t30-replace, ..., ft5 corresponding to? I unfortunately was not able to infer from the google drive folder what the different models were?
