### ISSUE TITLE
Follow-up question to new NegCLIP variants

### ISSUE THREAD

**Issue by vishaal27** [RAIVNLab/sugar-crepe#2]
Hi, I also added the following question in #1, but it was closed and I wasn't able to re-open it:

I have a question regarding the specific models you trained---what are the different models like t30-swap, t30-replace, ..., ft5 corresponding to? I unfortunately was not able to infer from the google drive folder what the different models were?

**Comment by vishaal27** [comment]
After taking a look again at the paper (specifically table 5), it seems like the model to row-in-the-table mapping is something like this:

1) t30-swap : NegCLIP from scratch trained on swap (row 10 in tab. 5)
2) t30-replace : NegCLIP from scratch trained on replace (row 9 in tab. 5)
3) t30-negate : NegCLIP from scratch trained on negate (row 11 in tab. 5)
4) t30 : NegCLIP from scratch trained on rep + sw + neg (row 12 in tab. 5)
5) ft5-swap : NegCLIP fine-tuned on swap (row 5 in tab. 5)
6) ft5-replace : NegCLIP fine-tuned on replace (row 4 in tab. 5)
7) ft5-negate : NegCLIP fine-tuned on negate (row 6 in tab. 5)

However, I am still unsure about the ft5 checkpoints you provided in the google drive folder, are these fine-tuned on rep + sw + neg? It seems like you don't report the numbers for this checkpoint in tab. 5 right? Could you clarify this please? Thanks!

**Comment by JieyuZ2** [comment]
oh sorry the t30 and ft5 are both trained with original CLIP objective, not NegCLIP

**Comment by JieyuZ2** [comment]
and your other mappings are correct

**Comment by vishaal27** [comment]
I see, so t30 is row 8 and ft5 is row 3 in table 5 right? And also for both models, the training datasets were coco train set right?

**Comment by JieyuZ2** [comment]
yes and yes
