### ISSUE TITLE
Table 5 values but broken down into obj, attr, and rel

### ISSUE THREAD

**Issue by bryant1410** [RAIVNLab/sugar-crepe#3]
Do you folks have the values of NegCLIP on Table 5 from SugarCREPE but broken down? E.g., Replace-Obj, etc.

Also, are the SugarCREPE values from Table 5 a micro-average of the broken down values?

**Comment by JieyuZ2** [comment]
yes it is micro-average, will post the broken-down values asap

**Comment by JieyuZ2** [comment]
Table-5 RN50 train from scratch | SugarCrepe

| Hard-negative | Replace-obj | Replace-att  | Replace-rel  | Swap-obj  | Swap-att | Add-obj  | Add-att  |
|:--------|:---------|:------|:------|:------|:-------------|:-------|:-------|
| - | 78.55 | 70.60 | 67.02 | 58.13 | 61.76  | 72.08 | 67.20 |
| Replace | 79.48 | 74.37 | 68.23 | 60.30 | 63.51 | 73.91 | 69.99 |
| Swap | 78.45 | 71.49 | 68.30 | 73.12 | 68.40 | 73.12 | 68.40 |
| Negate | 78.91 | 72.04 | 65.88 | 60.70 | 60.96 | 71.77 | 66.57 |
| Rep+Sw+Neg | 80.02 | 74.75 | 69.94 | 65.31 | 68.57 | 73.91 | 70.62 |

**Comment by JieyuZ2** [comment]
Table-5 ViT-B-32 fine-tune from OpenAI checkpoint | SugarCrepe

| Model | Replace-obj | Replace-att  | Replace-rel  | Swap-obj  | Swap-att | Add-obj  | Add-att  |
|:--------|:---------|:------|:------|:------|:-------------|:-------|:-------|
| OpenAI | 90.92 | 80.08 | 69.20 | 61.38 | 63.96 | 77.20 | 68.79 |
| Normal FT | 93.58 | 85.79 | 73.83 | 68.29 | 71.77 | 88.12 | 78.03 |
| NegCLIP FT | 92.68 | 85.91 | 76.46 | 75.20 | 75.38 | 88.80 | 82.80 |
| Replace | 93.46 | 90.36 | 81.01 | 73.98 | 75.23 | 90.93 | 87.86 |
| Swap | 93.52 | 86.68 | 75.533 | 74.80 | 76.73 | 88.99 | 79.34 |
| Negate | 93.58 | 85.53 | 74.54 | 67.48 | 71.32 | 88.46 | 78.03 |

**Comment by bryant1410** [comment]
Thanks!!!

> Table-5 ViT-b-16 fine-tune from OpenAI checkpoint | SugarCrepe

It's ViT-B/32, right?

**Comment by JieyuZ2** [comment]
> Thanks!!!
> 
> > Table-5 ViT-b-16 fine-tune from OpenAI checkpoint | SugarCrepe
> 
> It's ViT-B/32, right?

Yes, nice catch!
