### ISSUE TITLE
Access to the hard negatives used during fine-tuning

### ISSUE THREAD

**Issue by IMirandaM** [RAIVNLab/sugar-crepe#4]
Would it be possible to have access to the hard negatives used during fine-tuning?

**Comment by JieyuZ2** [comment]
sure, it is generated via CREPE pipeline, will add them soon

**Comment by JieyuZ2** [comment]
please find those data here: https://drive.google.com/drive/folders/1ZiTSFx8HtztOi_rZ30sM9Ek1yQaWnCaR?usp=sharing

**Comment by bryant1410** [comment]
`train2017_hn_atomic.csv` was the one used for the hard negative REPLACE, right?

**Comment by JieyuZ2** [comment]
> `train2017_hn_atomic.csv` was the one used for the hard negative REPLACE, right?

yes
